version: '3.3'

volumes:
  pg_data:
  static:
  media:
  import_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
  backend:
    container_name: foodgram-backend
    depends_on:
      - db
    image: kldaniil/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/user_media
      - ./data:/data
  frontend:
    container_name: foodgram-frontend
    env_file:
      - .env
    image: kldaniil/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    depends_on:
      - backend
    container_name: foodgram-nginx
    image: kldaniil/foodgram_nginx
    env_file:
      - .env
    ports:
      - "8003:80"
    volumes:
      - static:/static
      - media:/media
