# version: '3.3'
# services:

#   frontend:
#     container_name: foodgram-front
#     build: ../frontend
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     container_name: foodgram-proxy
#     image: nginx:1.25.4-alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/
version: '3.3'

volumes:
  pg_data:
  static:
  media:
  import_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    depends_on:
      - db
    build: ./backend/
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/user_media
  frontend:
    container_name: foodgram-frontend
    env_file:
      - .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    depends_on:
      - backend
    container_name: foodgram-nginx
    build: ./infra/
    env_file:
      - .env
    ports:
      - "8003:80"
    volumes:
      - static:/static
      - media:/media
